name: Deploy Image to GHCR

on:
  push:
    paths:
      - Dockerfile
      - start.sh
  workflow_dispatch:    

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GH_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/ralisoft/github-actions-runner:latest
          docker push ghcr.io/ralisoft/github-actions-runner:latest